export const ROLES = {
    USER: 'USER',
    SHOP_ADMIN: 'SHOP_ADMIN',
    SUPER_ADMIN: 'SUPER_ADMIN'
};

export const ORDER_TYPES = {
    DINE_IN: 'DINE_IN',
    DELIVERY: 'DELIVERY'
};

export const ORDER_STATUS = {
    PLACED: 'PLACED',
    PREPARING: 'PREPARING',
    READY: 'READY',
    OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
    DELIVERED: 'DELIVERED',
    COMPLETED: 'COMPLETED',
    REJECTED: 'REJECTED'
};

export const PAYMENT_STATUS = {
    NOT_REQUIRED: 'NOT_REQUIRED',
    SIMULATED_PAID: 'SIMULATED_PAID',
    REFUNDED: 'REFUNDED'
};

export const DELIVERY_SLOTS = ['10:30', '12:45', '15:30'];
